DRMDEMO/urls.py
from django.conf.global_settings import STATIC_ROOT
from django.contrib import admin
from django.urls import path, re_path
# from django.views.decorators.csrf import csrf_exempt
from django.views.static import serve
from django.conf.urls import url, include
from DRMDEMO.settings import MEDIA_ROOT

from apps.users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView, \
    LogoutView, MusicianListView, MusicianDetailView
from apps.operations.views import IndexView
from django.views.generic.base import RedirectView
from apps.music.views import PriceIntroduceView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    re_path('active/(?P<active_code>.*)/', ActiveUserView.as_view(), name='user_active'),
    path('forget/', ForgetPwdView.as_view(), name='forget_pwd'),
    re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name='reset_pwd'),
    path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {"document_root":STATIC_ROOT}),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    # 个人相关页面
    url(r'^users/', include(('apps.users.urls', "users"), namespace="users")),

    # 音乐相关页面
    url(r'^music/', include(('apps.music.urls', "music"), namespace="music")),

    # 用户相关操作
    url(r'^op/', include(('apps.operations.urls', "operations"), namespace="op")),

    # 版权发布者相关页面

    url(r'^musician/$', MusicianListView.as_view(), name="musician"),
    url(r'^musician/(?P<musician_id>\d+)/$', MusicianDetailView.as_view(), name="musician_detail"),

    path('', IndexView.as_view(), name='index'),

    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/images/reform/favicon.ico')),
    # path('receiveuploadsystem/',csrf_exempt(views.receiveuploadsystem),name = 'receiveuploadsystem'),

    # 首页后两个页面
    path('priceintroduce/',PriceIntroduceView.as_view(),name = 'priceintroduce'),
    # path('howtostart/',HowToStartView.as_view(),name='howtostart'),


]

apps/music/urls.py
from django.urls import path
from django.conf.urls import url
from apps.music import views
from apps.music.views import MusicListView, MusicDetailView, ModifyMyMuiscInfoView
from apps.operations.views import PurchaseOneView

urlpatterns = [
    url(r'^musiclist/$', MusicListView.as_view(), name="musiclist"),
    url(r'^(?P<music_id>\d+)/$', MusicDetailView.as_view(), name="detail"),
    # 用户购买
    path("purchaseone/", PurchaseOneView.as_view(), name='purchaseone'),
    # 用户退款
    # path("refundmoney/",RefundMoneyView.as_view(),name='refundmoney'),
    # 修改版权状态
    # path("modifymusic/", ModifyMusicView.as_view(), name='modifymusic'),
    # url(r'^(?P<course_id>\d+)/comments/$', MusicCommentsView.as_view(), name="comments"),
    # 发表评论
    url(r'^comment/$', views.CommentMusic, name="comment"),
    # 删除评论
    path('deletecomm/',views.DeleteComment,name='deletecomm'),
    path('modifymymuiscinfo/',ModifyMyMuiscInfoView.as_view(),name='modifymymuiscinfo'),
]

apps/operations/urls.py
from django.urls import path
from django.conf.urls import url

from apps.operations.views import AddFavView

urlpatterns = [
    # 添加收藏
    url(r'^fav/$', AddFavView.as_view(), name="fav"),

]

apps/users/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from apps.operations.views import UploadMusicView, UploadOneView, MyPurMusicView, \
    UpdateMyPermissionOneView, PurDetialDownView, DownloadKeyView, MusicianHomeView, \
    MusicianMusicView, MusicianMusicDetial, UploadFileView
from apps.users.views import UserInfoView, UploadImageView, ChangePwdView, SendEmailCodeView, UpdateEmailView, \
    UpdateKeyView, UpdateKeyValueView, MyFavView, MyFavMusicianView, MyMessageView,ModifyFreestyle
from apps.operations import views

urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name="info"),
    url(r'^image/upload/$', UploadImageView.as_view(), name="image"),
    url(r'^update/pwd/$', ChangePwdView.as_view(), name="update_pwd"),
    # 发送邮箱验证码
    path("sendemail_code/", SendEmailCodeView.as_view(), name='sendemail_code'),
    # 修改邮箱
    path("update_email/", UpdateEmailView.as_view(), name='update_email'),
    # 生成新交易账户
    path("update_key/", UpdateKeyView.as_view(), name='update_key'),
    path("update_value/", csrf_exempt(UpdateKeyValueView.as_view()), name='update_value'),
    # 发布我的音乐版权
    path("uploadmusic/", UploadMusicView.as_view(), name='uploadmusic'),
    # 上传版权
    path("uploadone/", UploadOneView.as_view(), name='uploadone'),
    # 上传文件
    path("uploadfile/", UploadFileView.as_view(), name='uploadfile'),
    # 我的音乐
    url(r'^mypurchase_music/$', MyPurMusicView.as_view(), name='mypurchase_music'),
    # 更新音乐权限
    path('updatemusic/', UpdateMyPermissionOneView.as_view(), name='updatemusic'),
    # 下载购买详情
    path('purdetialdown/', PurDetialDownView.as_view(), name='purdetialdown'),
    # 下载密钥
    path('downloadkey/', DownloadKeyView.as_view(), name='downloadkey'),
    # 我的收藏
    url(r'^myfav/$', MyFavView.as_view(), name="myfav"),
    url(r'^myfav_musician/$', MyFavMusicianView.as_view(), name="myfav_musician"),
    # 发布版权信息中心
    path('musicianhome/', MusicianHomeView.as_view(), name='musicianhome'),
    # 发布的版权
    path('musicianmusic/', MusicianMusicView.as_view(), name='musicianmusic'),
    # 版权发布者查看版权具体信息
    path('musicianmusicdetial/', MusicianMusicDetial.as_view(), name='musicianmusicdetial'),
    path('musicianmusicsolddetial/', views.musicianmusicsolddetial, name='musicianmusicsolddetial'),
    # 我的消息
    url(r'^messages/$', MyMessageView.as_view(), name="messages"),
    # 修改freestyle
    path('modifyfreestyle/', ModifyFreestyle.as_view(), name='modifyfreestyle')
]

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}区块链音乐版权平台{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/music.css' %}">
    {% block custom_css %}
    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>


</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>区块链+音乐=<b>区块链数字版权在线</b></p></div>
                    <!--登录后跳转-->
                    {% if user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{% if user.nick_name %}{{ user.nick_name }}{% else %}
                                    {{ user.username }}{% endif %}<img class="down fr"
                                                                       src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ user.image.url }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ user.image.url }}"/></dt>
                                    <dd>
                                        <h2>{{ user.nick_name }}</h2>
                                        <p>{{ user.username }}</p>
                                        {% if user.is_producter %}
                                            <div class="btn">
                                                <a class="fr" style="margin-top: -15px; margin-left: 70px;width: 200px"
                                                   href="{% url 'users:uploadmusic' %}">发布我的音乐版权</a>
                                            </div>
                                        {% endif %}
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}
                    {#                        <a href="{% url 'users:messages' %}">#}
                    {#                            <div class="msg-num"><span id="MsgNum">{{ unread_nums }}</span></div>#}
                    {#                        </a>#}
                </div>
            </div>

            <div class="middle">
                <div class="wp">
                    <a href={% url 'index' %}><img class="fl" src="{% static 'images/reform/logofinal2.png' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption"
                                  data-value="{% if s_type %}{{ s_type }}{% else %}原创音乐{% endif %}">
                                {% if s_type == 'music' %}原创音乐{% endif %}
                                {% if s_type == 'musician' %}音乐人{% endif %}
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="music">原创音乐</li>
                                <li data-value="musician">音乐人</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="{{ keywords }}"
                               placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li class="{% if request.path == '/' %}active{% endif %}"><a href="{% url 'index' %}">首页</a>
                            </li>
                            <li class="{% if request.path|slice:'20' == '/users/updatemusic/' %}active{% endif %}{% if request.path|slice:'7' == '/music/' %}active{% endif %}">
                                <a href="{% url 'music:musiclist' %}">
                                    原创音乐
                                </a>
                            </li>
                            <li class="{% if request.path|slice:'9' == '/musician' %}active{% endif %}">
                                <a href="{% url 'musician' %} ">音乐人</a>
                            </li>
                            <li class="{% if request.path|slice:'13' != '/org/teachers' %}{% if request.path|slice:'4' == '/org' %}active{% endif %}{% endif %}">
                                <a href="">如何开始？</a></li>
                            <li class="{% if request.path|slice:'16' == '/priceintroduce/' %}active{% endif %}">
                                <a href="{% url 'priceintroduce' %}">价格&授权</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
{% endblock %}

{% block content %}
{% endblock %}

<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="{% static 'images/reform/logobottom.png' %}"/></a></li>
                <li class="code"><img src="{% static 'images/tell1.png' %}"/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/>
                    <p class="tell">13072740511</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">2020 www.ginyz.com 区块链音乐版权-在线音乐版权交流平台 保留所有权利</span>
            <span class="fr">copyright  2020 ICP备案证书号：鄂ICP备xxxxx号-1</span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
{#        <li class="qq">#}
{#            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>#}
{#        </li>#}
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
{% block custom_js %}
{% endblock %}


</body>
</html>

templates/howtostart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/usercenter-base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}个人信息- 区块链音乐版权平台{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lq.datetimepick.css' %}"/>
    {% block custom_css %}
    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
        <div class="header2 header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>区块链+音乐=<b>区块链数字版权在线</b></p></div>
                    <!--登录后跳转-->
                    {% if user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{% if user.nick_name %}{{ user.nick_name }}{% else %}
                                    {{ user.username }}{% endif %}<img class="down fr"
                                                                       src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ user.image.url }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ user.image.url }}"/></dt>
                                    <dd>
                                        <h2>{{ user.nick_name }}</h2>
                                        <p>{{ user.username }}</p>
                                        {% if user.is_producter %}
                                            <div class="btn">
                                                <a class="fr" style="margin-top: -15px; margin-left: 70px;width: 200px"
                                                   href="{% url 'users:uploadmusic' %}">发布我的音乐版权</a>
                                            </div>
                                        {% endif %}
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}
                    <a href="{% url 'users:messages' %}">
                        <div class="msg-num"><span id="MsgNum">{{ unread_nums }}</span></div>
                    </a>
                </div>
            </div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/reform/logofinal2.png' %}"/></a>
                    <h1>我的区块链音乐版权平台</h1>
                </div>
            </div>
        </div>
    </header>
</section>

<!--crumbs start-->
{% block custom_bread %}

{% endblock %}
<section>
    <div class="wp list personal_list">
        <div class="left">
            <ul>
                <li class="{% if current_page == 'info' %}active2{% endif %}"><a href="{% url 'users:info' %}">个人信息</a>
                </li>
                <li class="{% if current_page == 'mycourse' %}active2{% endif %}"><a
                        href="{% url 'users:mypurchase_music' %}">我的音乐</a></li>
                <li class="{% if current_page == 'myfav' or current_page == 'myfav_musician' %}active2{% endif %}">
                    <a href="{% url 'users:myfav' %}">我的收藏</a></li>
                <li class="{% if current_page == 'message' %}active2{% endif %}">
                    <a href="{% url 'users:messages' %}" style="position: relative;">
                        我的消息
                    </a>
                </li>
                {% if user.is_producter %}
                    <li class="{% if current_page == 'musicianhome' %}active2{% endif %}"><a
                            href="{% url 'users:musicianhome' %}">版权首页</a>
                    <li class="{% if current_page == 'musicianmusic' %}active2{% endif %}"><a
                            href="{% url 'users:musicianmusic' %}">我发布的版权</a>
                    <li class="{% if current_page == 'uploadmusic' %}active2{% endif %}"><a
                        href="{% url 'users:uploadmusic' %}">版权发布</a>
                {% endif %}
            </ul>
        </div>
        {% block rigt_form %}

        {% endblock %}
    </div>
</section>

{% block layui %}

{% endblock %}



<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}" type="text/javascript"></script>
<script src='{% static "js/plugins/jquery.upload.js" %}' type='text/javascript'></script>

<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>


{#<script>#}
{#    var shareUrl = '',#}
{#        shareText = '',#}
{#        shareDesc = '',#}
{#        shareComment = '';#}
{#    $(function () {#}
{#        $(".bdsharebuttonbox a").mouseover(function () {#}
{#            var type = $(this).attr('data-cmd'),#}
{#                $parent = $(this).parent('.bdsharebuttonbox'),#}
{#                fxurl = $parent.attr('data-url'),#}
{#                fxtext = $parent.attr('data-text'),#}
{#                fxdesc = $parent.attr('data-desc'),#}
{#                fxcomment = $parent.attr('data-comment');#}
{#            switch (type) {#}
{#                case 'tsina':#}
{#                case 'tqq':#}
{#                case 'renren':#}
{#                    shareUrl = fxurl;#}
{#                    shareText = fxdesc;#}
{#                    shareDesc = '';#}
{#                    shareComment = '';#}
{#                    break;#}
{#                default :#}
{#                    shareUrl = fxurl;#}
{#                    shareText = fxtext;#}
{#                    shareDesc = fxdesc;#}
{#                    shareComment = fxcomment;#}
{#                    break;#}
{#            }#}
{#        });#}
{#    });#}
{##}
{#    function SetShareUrl(cmd, config) {#}
{#        if (shareUrl) {#}
{#            config.bdUrl = "" + shareUrl;#}
{#        }#}
{#        if (shareText) {#}
{#            config.bdText = shareText;#}
{#        }#}
{#        if (shareDesc) {#}
{#            config.bdDesc = shareDesc;#}
{#        }#}
{#        if (shareComment) {#}
{#            config.bdComment = shareComment;#}
{#        }#}
{##}
{#        return config;#}
{#    }#}
{##}
{#    window._bd_share_config = {#}
{#        "common": {#}
{#            "onBeforeClick": SetShareUrl,#}
{#            "bdPic": "",#}
{#            "bdMini": "2",#}
{#            "searchPic": "1",#}
{#            "bdMiniList": false#}
{#        },#}
{#        "share": {#}
{#            "bdSize": "16"#}
{#        }#}
{#    };#}
{#    with (document) 0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com../api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];#}
{#</script>#}
{% block custom_js %}
{% endblock %}
</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% block title %}我的收藏- 区块链音乐版权平台{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
     <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block rigt_form %}
      <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:myfavorg' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:myfav_teachers' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in course_list %}
                        <div class="module1_5 box" style="height: auto">
                            <a href="{% url 'course:detail' course.id %}">
                                <img width="214" height="214" src="{{ course.image.url }}" style="height: 214px"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

{% block custom_js %}
<script type="text/javascript">
    $('.jsDeleteFav_course').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'op:fav' %}",
                data: {
                    fav_type: 1,
                    fav_id: favid,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
</script>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% block title %}我的收藏- 区块链音乐版权平台{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block rigt_form %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>

        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="active"><a href="{% url 'users:myfav' %}">音乐</a></li>
                    <li><a href="{% url 'users:myfav_musician' %}">音乐人 </a></li>
                </ul>
            </div>
            <div class="companycenter">
                <div class="group_list brief">
                    {% for music in music_list.object_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'music:detail' music.id %}">
                                <img width="214" height="214" src="{{ music.image.url }}" style="height: 214px"/>
                            </a>
                            <div class="desdemo2">
                                <a href="{% url 'music:detail' music.id %}">
                                    <h2>{{ music.music_name }}</h2>
                                </a>
                                <span class="fl" style="width: 214px;height:24px;overflow: hidden">流派：{% for tag in music.music_tag %}
                                    {{ tag.show_name }}
                                {% endfor %}</span>
                                <span class="fl3">价格(ETH)：{{ music.music_price1 }}&nbsp;&nbsp;起&nbsp;</span>
                                <span class="fr">购买人数：{{ music.all_sell_count }}&nbsp;&nbsp;</span>

                            </div>
                            <div class="bottom">
                                <span class="fl">{{ music.owner.nick_name }}</span>
                                <span class="delete-group fr jsDeleteFav_music" data-favid="{{ music.id }}"></span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
          <div class="pageturn">
                <ul class="pagelist">
                    {% if music_list.has_previous %}
                        <li class="long"><a href="?{{ music_list.previous_page_number.querystring }}">上一页</a></li>
                    {% endif %}

                    {% for page in music_list.pages %}
                        {% if page %}
                            {% ifequal page music_list.number %}
                                <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                            {% else %}
                                <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                            {% endifequal %}
                        {% else %}
                            <li class="none">...</li>
                        {% endif %}
                    {% endfor %}
                    {% if music_list.has_next %}
                        <li class="long"><a href="?{{ music_list.next_page_number.querystring }}">下一页</a></li>
                    {% endif %}
                </ul>
            </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        $('.jsDeleteFav_music').on('click', function () {
            var _this = $(this),
                favid = _this.attr('data-favid');
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'op:fav' %}",
                data: {
                    fav_type: 1,
                    fav_id: favid,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                async: true,
                success: function (data) {
                    Dml.fun.winReload();
                }
            });
        });
    </script>
{% endblock %}